# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20170227_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='vat_rate_type',
            field=models.CharField(default='standard', max_length=60, verbose_name='vat rate type'),
        ),
    ]
