# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productclass_vat_rate_type'),
        ('product', '0033_auto_20170227_0757'),
    ]

    operations = [
    ]
