# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_merge_20170920_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.FloatField(null=True, verbose_name='mass in kg'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mass_override',
            field=models.FloatField(null=True, verbose_name='mass in kg'),
        ),
    ]
