# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20170920_2122'),
        ('product', '0035_auto_20170919_0846'),
    ]

    operations = [
    ]
