# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:35
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_merge_20170929_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.PriceField(currency='EUR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
    ]
