# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170906_0556'),
        ('cart', '0003_auto_20170920_1119'),
    ]

    operations = [
    ]
