# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20170920_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='en-gb', max_length=35),
        ),
    ]
